---
title: steffano santiago chavez
author: steffano santiago chavez
email: email@steffanochavez.com
description: lorem ipsum
baseurl: "/"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
